# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.1.0

pipelines:
  branches:
    AI-*:
      - step:
         deployment: test
         caches:
          - node
         script: # Modify the commands below to build your repository.
          - yarn run global
          - yarn install
          - mkdir -p .docs
          - yarn lint
          - yarn test:integration
          - mkdir test-report
          - mv test-report.html test-report/index.html
          - apt-get update && apt-get install -y python-dev
          - apt-get install -y python-dev
          - curl -O https://bootstrap.pypa.io/get-pip.py
          - python get-pip.py
          - pip install awscli
          - yarn build
          - yarn build-storybook
          - aws s3 sync --delete ./coverage s3://reports.qa.youngapp.co/uikit/$BITBUCKET_BRANCH/coverage --acl bucket-owner-full-control --acl public-read
          - aws s3 sync --delete ./test-report s3://reports.qa.youngapp.co/uikit/$BITBUCKET_BRANCH/report --acl bucket-owner-full-control --acl public-read
          - aws s3 sync --delete ./storybook-static s3://reports.qa.youngapp.co/uikit/$BITBUCKET_BRANCH/storybook --acl bucket-owner-full-control --acl public-read
    develop:
      - step:
         deployment: test
         caches:
          - node
         script: # Modify the commands below to build your repository.
          - yarn run global
          - yarn install
          - mkdir -p .docs
          - yarn lint
          - yarn test:integration
          - mkdir test-report
          - mv test-report.html test-report/index.html
          - apt-get update && apt-get install -y python-dev
          - apt-get install -y python-dev
          - curl -O https://bootstrap.pypa.io/get-pip.py
          - python get-pip.py
          - pip install awscli
          - yarn build
          - yarn build-storybook
          - aws s3 sync --delete ./coverage s3://reports.qa.youngapp.co/uikit/$BITBUCKET_BRANCH/coverage --acl bucket-owner-full-control --acl public-read
          - aws s3 sync --delete ./test-report s3://reports.qa.youngapp.co/uikit/$BITBUCKET_BRANCH/report --acl bucket-owner-full-control --acl public-read
          - aws s3 sync --delete ./storybook-static s3://reports.qa.youngapp.co/uikit/$BITBUCKET_BRANCH/storybook --acl bucket-owner-full-control --acl public-read
    master:
      - step:
         deployment: production
         caches:
          - node
         script: # Modify the commands below to build your repository.
          - yarn run global
          - yarn install
          - yarn lint
          - yarn test:integration
          - yarn build
          - yarn release
          - printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc
          - export NPM_TOKEN="2e54affd-eb69-4d58-b4ba-4dbe373410ba"
          - 'echo "//registry.npmjs.org/:_authToken=2e54affd-eb69-4d58-b4ba-4dbe373410ba" > ~/.npmrc'
          - npm publish
          - git push --follow-tags origin master
          - git fetch --unshallow
          - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
          - git fetch origin
          - git checkout --track origin/develop
          - git merge --no-ff master
          - git commit --amend -m "chore(release) - [skip ci]"
          - git push origin develop