# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.1.0

pipelines:
  branches:
    develop:
      - step:
         deployment: test
         caches:
          - node
         script: # Modify the commands below to build your repository.
          - yarn run global
          - yarn install
          - mkdir -p .docs
          - yarn lint
          - yarn test
          - mkdir test-report
          - mv test-report.html test-report/index.html
          - apt-get update && apt-get install -y python-dev
          - apt-get install -y python-dev
          - curl -O https://bootstrap.pypa.io/get-pip.py
          - python get-pip.py
          - pip install awscli
          - yarn build
          - aws s3 sync --delete ./coverage s3://reports.qa.youngapp.co/uikit/coverage --acl bucket-owner-full-control --acl public-read
          - aws s3 sync --delete ./test-report s3://reports.qa.youngapp.co/uikit/report --acl bucket-owner-full-control --acl public-read
    master:
      - step:
         deployment: production
         caches:
          - node
         script: # Modify the commands below to build your repository.
          - yarn run global
          - yarn install
          - yarn lint
          - yarn test
          - apt-get update && apt-get install -y python-dev
          - apt-get install -y python-dev
          - curl -O https://bootstrap.pypa.io/get-pip.py
          - python get-pip.py
          - pip install awscli
          - yarn build


## Execute Ghost Inspector suite via API and store results in JSON file
# curl "https://api.ghostinspector.com/v1/suites/$GHOST_SUITE_ID/execute/?apiKey=$GHOST_API_KEY" > ghostinspector.json
## Check JSON results for failing tests
# if [ $(grep -c '"passing":false' ghostinspector.json) -ne 0 ]; then false; else echo "Tests Passed"; fi
