"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var react_1 = __importDefault(require("react"));
var index_1 = require("../index");
/**
 * Typography render element
 */
var Typography = function () { return (react_1.default.createElement("div", { style: { height: '100%', margin: '5%' } },
    react_1.default.createElement("div", { style: { height: '80%', padding: '2%' } },
        react_1.default.createElement("h1", null, "Typography"),
        react_1.default.createElement("hr", null)),
    react_1.default.createElement("div", { style: { padding: '2%' } },
        react_1.default.createElement("p", null, "Hello World!!"),
        react_1.default.createElement("p", null, "An Adptable Foundation")),
    react_1.default.createElement("div", { style: { width: '100%', padding: '2%' } },
        react_1.default.createElement("div", { style: { float: 'left', width: "50%", paddingRight: "5%" } },
            react_1.default.createElement("p", null, "Heading 3"),
            react_1.default.createElement("p", { style: { color: 'green' } }, "Create a list with all possible keywords that fit to your product,services orbussiness field. The more the better.So you will get also a lot of keywords which you must pay for only the minimal."),
            react_1.default.createElement("p", { style: { color: 'green', paddingTop: '5%' } }, "Benifit frommisspelling in i\\orser to find keywords which your competitors didnot think of For example if you have aemergencyservices, do not only bid for \"emergency\" but also for \"imergency\"")),
        react_1.default.createElement("div", { style: { paddingRight: '5%' } },
            react_1.default.createElement("p", null, "Heading 4"),
            react_1.default.createElement("p", { style: { color: 'green' } }, "Create a list with all possible keywords that fit to your product,services orbussiness field. The more the better.So you will get also a lot of keywords which you must pay for only the minimal."),
            react_1.default.createElement("p", { style: { marginTop: "5%" } }, "Heading 5"),
            react_1.default.createElement("p", { style: { marginTop: '0px', display: 'block' } }, "Create a list with all possible keywords that fit to your product,services orbussiness field."))),
    react_1.default.createElement("div", { style: { width: '100%', marginTop: '5%' } },
        react_1.default.createElement("div", { style: { width: '100%', } },
            react_1.default.createElement("div", { style: { float: 'left' } },
                react_1.default.createElement("h1", null, "H1/Rubick regular")),
            react_1.default.createElement("div", { style: { marginTop: '2%', float: 'right', paddingRight: '5%' } },
                react_1.default.createElement("p", { style: { fontSize: '30px' } }, "30px")),
            react_1.default.createElement("div", { style: { clear: 'both' } })),
        react_1.default.createElement("hr", null),
        react_1.default.createElement("div", { style: { width: '100%' } },
            react_1.default.createElement("div", { style: { float: 'left' } },
                react_1.default.createElement("h2", null, "H2/Rubick regular")),
            react_1.default.createElement("div", { style: { marginTop: '2%', float: 'right', paddingRight: '5%' } },
                react_1.default.createElement("p", { style: { fontSize: '26px' } }, "26px")),
            react_1.default.createElement("div", { style: { clear: 'both' } })),
        react_1.default.createElement("hr", null),
        react_1.default.createElement("div", { style: { width: '100%' } },
            react_1.default.createElement("div", { style: { float: 'left' } },
                react_1.default.createElement("h3", null, "H3/Rubick regular")),
            react_1.default.createElement("div", { style: { marginTop: '2%', float: 'right', paddingRight: '5%' } },
                react_1.default.createElement("p", { style: { fontSize: '20px' } }, "20px")),
            react_1.default.createElement("div", { style: { clear: 'both' } })),
        react_1.default.createElement("hr", null),
        react_1.default.createElement("div", { style: { width: '100%' } },
            react_1.default.createElement("div", { style: { float: 'left' } },
                react_1.default.createElement("h4", null, "H4/Rubick regular")),
            react_1.default.createElement("div", { style: { marginTop: '2%', float: 'right', paddingRight: '5%' } },
                react_1.default.createElement("p", { style: { fontSize: '18px' } }, "18px")),
            react_1.default.createElement("div", { style: { clear: 'both' } })),
        react_1.default.createElement("hr", null),
        react_1.default.createElement("div", { style: { width: '100%' } },
            react_1.default.createElement("div", { style: { float: 'left' } },
                react_1.default.createElement("h5", null, "H5/Rubick regular")),
            react_1.default.createElement("div", { style: { marginTop: '2%', float: 'right', paddingRight: '5%' } },
                react_1.default.createElement("p", { style: { fontSize: '16px' } }, "16px")),
            react_1.default.createElement("div", { style: { clear: 'both' } })),
        react_1.default.createElement("hr", null),
        react_1.default.createElement("div", { style: { width: '100%' } },
            react_1.default.createElement("div", { style: { float: 'left' } },
                react_1.default.createElement("caption", null, "caption")),
            react_1.default.createElement("div", { style: { marginTop: '2%', float: 'right', paddingRight: '5%' } },
                react_1.default.createElement("p", { style: { fontSize: '14px' } }, "14px")),
            react_1.default.createElement("div", { style: { clear: 'both' } })),
        react_1.default.createElement("hr", null),
        react_1.default.createElement("div", { style: { width: '100%' } },
            react_1.default.createElement("div", { style: { float: 'left' } },
                react_1.default.createElement(index_1.Button, { value: 'Button label', color: "primary", style: { fontSize: '12px' } }, "Button label")),
            react_1.default.createElement("div", { style: { marginTop: '2%', float: 'right', paddingRight: '5%' } },
                react_1.default.createElement("p", { style: { fontSize: '12px' } }, "12px")),
            react_1.default.createElement("div", { style: { clear: 'both', } })),
        react_1.default.createElement("hr", null),
        react_1.default.createElement("div", { style: { width: '100%' } },
            react_1.default.createElement("div", { style: { float: 'left' } },
                react_1.default.createElement("p", { style: { fontSize: '14px' } }, "Text/Rubic light")),
            react_1.default.createElement("div", { style: { marginTop: '2%', float: 'right', paddingRight: '5%' } },
                react_1.default.createElement("p", { style: { fontSize: '14px' } }, "14px")),
            react_1.default.createElement("div", { style: { clear: 'both', } })),
        react_1.default.createElement("hr", null),
        react_1.default.createElement("div", { style: { width: '100%' } },
            react_1.default.createElement("div", { style: { float: 'left' } },
                react_1.default.createElement("a", { href: '#' }, " Text Link")),
            react_1.default.createElement("div", { style: { marginTop: '2%', float: 'right', paddingRight: '5%' } },
                react_1.default.createElement("p", { style: { fontSize: '14px' } }, "14px")),
            react_1.default.createElement("div", { style: { clear: 'both' } })),
        react_1.default.createElement("hr", null)))); };
exports.default = Typography;
//# sourceMappingURL=typography.js.map