import React from 'react';
import { Button } from '../index';
/**
 * Typography render element
 */
const Typography = () => (React.createElement("div", { style: { height: '100%', margin: '5%' } },
    React.createElement("div", { style: { height: '80%', padding: '2%' } },
        React.createElement("h1", null, "Typography"),
        React.createElement("hr", null)),
    React.createElement("div", { style: { padding: '2%' } },
        React.createElement("p", null, "Hello World!!"),
        React.createElement("p", null, "An Adptable Foundation")),
    React.createElement("div", { style: { width: '100%', padding: '2%' } },
        React.createElement("div", { style: { float: 'left', width: "50%", paddingRight: "5%" } },
            React.createElement("p", null, "Heading 3"),
            React.createElement("p", { style: { color: 'green' } }, "Create a list with all possible keywords that fit to your product,services orbussiness field. The more the better.So you will get also a lot of keywords which you must pay for only the minimal."),
            React.createElement("p", { style: { color: 'green', paddingTop: '5%' } }, "Benifit frommisspelling in i\\orser to find keywords which your competitors didnot think of For example if you have aemergencyservices, do not only bid for \"emergency\" but also for \"imergency\"")),
        React.createElement("div", { style: { paddingRight: '5%' } },
            React.createElement("p", null, "Heading 4"),
            React.createElement("p", { style: { color: 'green' } }, "Create a list with all possible keywords that fit to your product,services orbussiness field. The more the better.So you will get also a lot of keywords which you must pay for only the minimal."),
            React.createElement("p", { style: { marginTop: "5%" } }, "Heading 5"),
            React.createElement("p", { style: { marginTop: '0px', display: 'block' } }, "Create a list with all possible keywords that fit to your product,services orbussiness field."))),
    React.createElement("div", { style: { width: '100%', marginTop: '5%' } },
        React.createElement("div", { style: { width: '100%', } },
            React.createElement("div", { style: { float: 'left' } },
                React.createElement("h1", null, "H1/Rubick regular")),
            React.createElement("div", { style: { marginTop: '2%', float: 'right', paddingRight: '5%' } },
                React.createElement("p", { style: { fontSize: '30px' } }, "30px")),
            React.createElement("div", { style: { clear: 'both' } })),
        React.createElement("hr", null),
        React.createElement("div", { style: { width: '100%' } },
            React.createElement("div", { style: { float: 'left' } },
                React.createElement("h2", null, "H2/Rubick regular")),
            React.createElement("div", { style: { marginTop: '2%', float: 'right', paddingRight: '5%' } },
                React.createElement("p", { style: { fontSize: '26px' } }, "26px")),
            React.createElement("div", { style: { clear: 'both' } })),
        React.createElement("hr", null),
        React.createElement("div", { style: { width: '100%' } },
            React.createElement("div", { style: { float: 'left' } },
                React.createElement("h3", null, "H3/Rubick regular")),
            React.createElement("div", { style: { marginTop: '2%', float: 'right', paddingRight: '5%' } },
                React.createElement("p", { style: { fontSize: '20px' } }, "20px")),
            React.createElement("div", { style: { clear: 'both' } })),
        React.createElement("hr", null),
        React.createElement("div", { style: { width: '100%' } },
            React.createElement("div", { style: { float: 'left' } },
                React.createElement("h4", null, "H4/Rubick regular")),
            React.createElement("div", { style: { marginTop: '2%', float: 'right', paddingRight: '5%' } },
                React.createElement("p", { style: { fontSize: '18px' } }, "18px")),
            React.createElement("div", { style: { clear: 'both' } })),
        React.createElement("hr", null),
        React.createElement("div", { style: { width: '100%' } },
            React.createElement("div", { style: { float: 'left' } },
                React.createElement("h5", null, "H5/Rubick regular")),
            React.createElement("div", { style: { marginTop: '2%', float: 'right', paddingRight: '5%' } },
                React.createElement("p", { style: { fontSize: '16px' } }, "16px")),
            React.createElement("div", { style: { clear: 'both' } })),
        React.createElement("hr", null),
        React.createElement("div", { style: { width: '100%' } },
            React.createElement("div", { style: { float: 'left' } },
                React.createElement("caption", null, "caption")),
            React.createElement("div", { style: { marginTop: '2%', float: 'right', paddingRight: '5%' } },
                React.createElement("p", { style: { fontSize: '14px' } }, "14px")),
            React.createElement("div", { style: { clear: 'both' } })),
        React.createElement("hr", null),
        React.createElement("div", { style: { width: '100%' } },
            React.createElement("div", { style: { float: 'left' } },
                React.createElement(Button, { value: 'Button label', color: "primary", style: { fontSize: '12px' } }, "Button label")),
            React.createElement("div", { style: { marginTop: '2%', float: 'right', paddingRight: '5%' } },
                React.createElement("p", { style: { fontSize: '12px' } }, "12px")),
            React.createElement("div", { style: { clear: 'both', } })),
        React.createElement("hr", null),
        React.createElement("div", { style: { width: '100%' } },
            React.createElement("div", { style: { float: 'left' } },
                React.createElement("p", { style: { fontSize: '14px' } }, "Text/Rubic light")),
            React.createElement("div", { style: { marginTop: '2%', float: 'right', paddingRight: '5%' } },
                React.createElement("p", { style: { fontSize: '14px' } }, "14px")),
            React.createElement("div", { style: { clear: 'both', } })),
        React.createElement("hr", null),
        React.createElement("div", { style: { width: '100%' } },
            React.createElement("div", { style: { float: 'left' } },
                React.createElement("a", { href: '#' }, " Text Link")),
            React.createElement("div", { style: { marginTop: '2%', float: 'right', paddingRight: '5%' } },
                React.createElement("p", { style: { fontSize: '14px' } }, "14px")),
            React.createElement("div", { style: { clear: 'both' } })),
        React.createElement("hr", null))));
export default Typography;
//# sourceMappingURL=typography.js.map