"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var styled_components_1 = __importDefault(require("styled-components"));
exports.StyledSidebar = styled_components_1.default.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  flex-direction: column;\n  width: 250px;\n  border-right: solid 1px #eee;\n  height: 100vh;\n\n  .icon-nav-left {\n  }\n\n\n  .sidebar-item-text {\n    vertical-align: middle;\n    color: #212529;\n    a, a:hover {\n      color: #212529;\n      text-decoration: none;\n    }\n  }\n\n  .icon-nav-right {\n    float: right;\n    margin-right: 0rem;\n    margin-left: 0px;\n    svg {\n      margin: 0!important;\n    }\n  }\n\n  .nav-link {\n    padding: 0.7rem 1rem;\n    font-size: 0.9rem;\n    cursor: pointer;\n    border-left: solid 3px #fff;\n    &:hover {\n      background-color: #F6F6F6;\n      border-left: solid 3px #007bff!important;\n    }\n\n    svg:first-child {\n      margin-right: 20px;\n      margin-left: 10px;\n    }\n  }\n\n  .nav-item.active {\n    .nav-link {\n      color: #007bff;\n      background-color: rgba(0, 123, 255, 0.05);\n      border-left: solid 3px #007bff!important;\n      .sidebar-item-text {\n        color: #007bff;\n      }\n    }\n  }\n\n  .navbar-brand {\n    display: block;\n    padding: 1.2rem 1rem;\n    cursor: pointer;\n    margin-right: 0;\n    padding-left: 1.95rem;\n  }\n\n  .NavHeader {\n    display: block;\n    padding: 1.2rem 1rem;\n    cursor: pointer;\n    margin-right: 0;\n    padding-left: 1.95rem;\n    font-size: 1rem;\n    padding-bottom: 0.4rem;\n    color: #777;\n  }\n"], ["\n  flex-direction: column;\n  width: 250px;\n  border-right: solid 1px #eee;\n  height: 100vh;\n\n  .icon-nav-left {\n  }\n\n\n  .sidebar-item-text {\n    vertical-align: middle;\n    color: #212529;\n    a, a:hover {\n      color: #212529;\n      text-decoration: none;\n    }\n  }\n\n  .icon-nav-right {\n    float: right;\n    margin-right: 0rem;\n    margin-left: 0px;\n    svg {\n      margin: 0!important;\n    }\n  }\n\n  .nav-link {\n    padding: 0.7rem 1rem;\n    font-size: 0.9rem;\n    cursor: pointer;\n    border-left: solid 3px #fff;\n    &:hover {\n      background-color: #F6F6F6;\n      border-left: solid 3px #007bff!important;\n    }\n\n    svg:first-child {\n      margin-right: 20px;\n      margin-left: 10px;\n    }\n  }\n\n  .nav-item.active {\n    .nav-link {\n      color: #007bff;\n      background-color: rgba(0, 123, 255, 0.05);\n      border-left: solid 3px #007bff!important;\n      .sidebar-item-text {\n        color: #007bff;\n      }\n    }\n  }\n\n  .navbar-brand {\n    display: block;\n    padding: 1.2rem 1rem;\n    cursor: pointer;\n    margin-right: 0;\n    padding-left: 1.95rem;\n  }\n\n  .NavHeader {\n    display: block;\n    padding: 1.2rem 1rem;\n    cursor: pointer;\n    margin-right: 0;\n    padding-left: 1.95rem;\n    font-size: 1rem;\n    padding-bottom: 0.4rem;\n    color: #777;\n  }\n"])));
var templateObject_1;
//# sourceMappingURL=style.js.map